<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * ProblemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblemRepository extends \Doctrine\ORM\EntityRepository
{
    public function getResolved(User $user) {
        $qb = $this->createQueryBuilder('p');

        $query = $qb
            ->innerJoin('AppBundle:Solution', 's', 'WITH', 's.problem = p')
            ->andWhere('s.user = :user')
            ->setParameter('user', $user)
        ;

        $results = $query->getQuery()->getResult();

        return $results;
    }
}
