<?php

namespace AppBundle\Repository;

/**
 * ProblemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblemRepository extends \Doctrine\ORM\EntityRepository
{
}
