<?php

namespace AppBundle\Repository;

/**
 * TestResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestResultRepository extends \Doctrine\ORM\EntityRepository
{
}
